import sys
import StringIO
import itertools
import os


OUT = '''Head, shoulders, knees and toes
knees and toes
Head, shoulders, knees and toes
knees and toes
and eyes and ears and mouth and nose
Head, shoulders, knees and toes
knees and toes

..., shoulders, knees and toes
knees and toes
..., shoulders, knees and toes
knees and toes
and eyes and ears and mouth and nose
..., shoulders, knees and toes
knees and toes

..., ..., knees and toes
knees and toes
..., ..., knees and toes
knees and toes
and eyes and ears and mouth and nose
..., ..., knees and toes
knees and toes

..., ..., ... ... toes
... ... toes
..., ..., ... ... toes
... ... toes
and eyes and ears and mouth and nose
..., ..., ... ... toes
... ... toes

..., ..., ... ... ...
... ... ...
..., ..., ... ... ...
... ... ...
and eyes and ears and mouth and nose
..., ..., ... ... ...
... ... ...

..., ..., ... ... ...
... ... ...
..., ..., ... ... ...
... ... ...
... ... and ears and mouth and nose
..., ..., ... ... ...
... ... ...

..., ..., ... ... ...
... ... ...
..., ..., ... ... ...
... ... ...
... ... ... ... and mouth and nose
..., ..., ... ... ...
... ... ...

..., ..., ... ... ...
... ... ...
..., ..., ... ... ...
... ... ...
... ... ... ... ... ... ... nose
..., ..., ... ... ...
... ... ...

..., ..., ... ... ...
... ... ...
..., ..., ... ... ...
... ... ...
... ... ... ... ... ... ... ...
..., ..., ... ... ...
... ... ...'''

old_stdout = sys.stdout
new_stdout = StringIO.StringIO()
sys.stdout = new_stdout
import main
printed = new_stdout.getvalue().strip()
sys.stdout = old_stdout

if printed == OUT:
    print 'All Good'
    print os.path.getsize(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'main.py'))
else:
    for l_ref, l_attempt in itertools.izip_longest(OUT.splitlines(), printed.splitlines()):
        if l_ref != l_attempt:
            print 'BAD!'
            print l_ref
            print l_attempt
            break
        else:
            print l_ref
